name: Bug Report
description: File a bug report to help us improve TestPilot
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: TestPilot Version
      description: What version of TestPilot are you running?
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider were you using when the bug occurred?
      options:
        - OpenAI
        - Anthropic
        - Ollama
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use file '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please copy and paste any relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: files
    attributes:
      label: Sample Files
      description: If applicable, provide sample code files that reproduce the issue
      render: python
      placeholder: |
        # Sample code that causes the issue
        def example_function():
            pass

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your TestPilot configuration (remove any API keys!)
      render: json
      placeholder: |
        {
          "defaultProvider": "openai",
          "enhancedMode": true
        }

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included all necessary information above
          required: true
        - label: I have removed any sensitive information (API keys, personal data)
          required: true
        - label: I am using the latest version of TestPilot
          required: false